version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: curl -X POST $DOCKERHUB_TRIGGER_URL
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
